added repository for chat list and chats are saved to local db
nur-shuvo/SwapMind pull request #7
Opened 2024-01-02 15:51 UTC by wakilkhan96

2024-01-03 08:44 UTC, nur-shuvo commented on app/src/main/java/com/developerspace/webrtcsample/compose/repository/ChatRepository.kt
> +class ChatRepository @Inject constructor(
RecentChatListRepository will be more meaningful

2024-01-03 09:30 UTC, nur-shuvo commented on app/src/main/java/com/developerspace/webrtcsample/compose/repository/ChatRepository.kt
> +        db.reference.child(ChatMainActivity.ROOT).child(MainActivity.ONLINE_USER_LIST_CHILD).get()
This logic should be rewritten, no need of process of uidVsUserName now, we  have updates in DB. If you think, it can be done in this commit, do. or, add a TODO

2024-01-03 09:34 UTC, nur-shuvo commented on app/src/main/java/com/developerspace/webrtcsample/model/RecentMessage.kt
> +    var friendlyMessage: FriendlyMessage = FriendlyMessage()
Can we add readStatus boolean? And reflect in ChatListScreen?

2024-01-03 09:36 UTC, nur-shuvo requested changes

2024-01-03 09:36 UTC, nur-shuvo commented on app/src/main/java/com/developerspace/webrtcsample/model/RecentMessage.kt
> +    var friendlyMessage: FriendlyMessage = FriendlyMessage()
Also add  in DB entity?

2024-01-03 13:57 UTC, nur-shuvo commented on app/src/main/java/com/developerspace/webrtcsample/compose/repository/ChatRepository.kt
> +        db.reference.child(ChatMainActivity.ROOT).child(MainActivity.ONLINE_USER_LIST_CHILD).get()
Please change it to eventListener to always sync remote with db. Please check UserListRepo for reference

2024-01-06 15:24 UTC, wakilkhan96 commented on app/src/main/java/com/developerspace/webrtcsample/compose/repository/ChatRepository.kt
> +        db.reference.child(ChatMainActivity.ROOT).child(MainActivity.ONLINE_USER_LIST_CHILD).get()
no need now, user data collected from local db

2024-01-06 16:13 UTC, wakilkhan96 commented on app/src/main/java/com/developerspace/webrtcsample/model/RecentMessage.kt
> +    var friendlyMessage: FriendlyMessage = FriendlyMessage()
will do on next cl

2024-01-06 16:13 UTC, wakilkhan96 commented on app/src/main/java/com/developerspace/webrtcsample/compose/repository/ChatRepository.kt
> +        db.reference.child(ChatMainActivity.ROOT).child(MainActivity.ONLINE_USER_LIST_CHILD).get()
done

2024-01-07 06:44 UTC, nur-shuvo commented on app/src/main/java/com/developerspace/webrtcsample/compose/repository/ChatRepository.kt
> +            })
This block is not needed as userListRepository sync db with remote.

2024-01-07 07:47 UTC, wakilkhan96 commented on app/src/main/java/com/developerspace/webrtcsample/compose/repository/ChatRepository.kt
> +            })
Firstly i marked this block as TODO, later then I thought this block should be here. Reason is in future it may happen that active user list screen may need to be sacrificed to implement another must need feature. But chat list screen will never be obsoleted.

2024-01-07 08:01 UTC, merged